services:
  home-metrics:
    image: nsmith167/home-metrics:latest
    container_name: home-metrics
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - MQTT_CLIENTID=${MQTT_CLIENTID}
      - MQTT_TOPICS_WEATHER_NAME=${MQTT_TOPICS_WEATHER_NAME}
      - MQTT_TOPICS_TEMPHUMIDITY_NAME=${MQTT_TOPICS_TEMPHUMIDITY_NAME}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    ports:
      - "8080:8080"
  home-metrics-dashboard:
    image: nsmith167/home-metrics-dashboard:latest
    container_name: home-metrics-dashboard
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "8050:8050"
  weather-scanner:
    image: nsmith167/weather-scanner:latest
    container_name: weather-scanner
    network_mode: "host"
    restart: unless-stopped
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_ZIP=${WEATHER_ZIP}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - WEATHER_TOPIC=${MQTT_TOPICS_WEATHER_NAME}
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    network_mode: "host"
    restart: unless-stopped
  